Fixed GitHub autobuild script

diff --git a/.github/workflows/flutter_build.yml b/.github/workflows/flutter_build.yml
--- a/.github/workflows/flutter_build.yml
+++ b/.github/workflows/flutter_build.yml
@@ -34,17 +34,17 @@ jobs:
           java-version: "17"
           cache: "gradle"
 
-      # - name: Install Flutter
-      #   uses: subosito/flutter-action@v2
-      #   with:
-      #     flutter-version: "3.32.4"
-      #     cache: true
+      - name: Install Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: "3.32.4"
+          cache: true
 
-      # - name: Get Flutter dependencies
-      #   run: flutter pub get
+      - name: Get Flutter dependencies
+        run: flutter pub get
 
-      # - name: Analyze
-      #   run: flutter analyze
+      - name: Analyze
+        run: flutter analyze
 
       - name: Extract version and build number (Windows)
         id: extract_version_windows
@@ -91,87 +91,87 @@ jobs:
             exit 1
           }
 
-      # - name: Build APK
-      #   run: flutter build apk --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
+      - name: Build APK
+        run: flutter build apk --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
 
-      # - name: Rename APK
-      #   shell: pwsh
-      #   run: |
-      #     $version = '${{ steps.extract_version_windows.outputs.version }}'
-      #     $build = '${{ steps.extract_version_windows.outputs.build }}'
-      #     $sourcePath = 'build/app/outputs/flutter-apk/app-release.apk'
-      #     $destFileName = "Revelation-android-$version-$build.apk"
-      #     $destPath = "build/app/outputs/flutter-apk/$destFileName"
-      #     Write-Output "Renaming $sourcePath to $destPath"
-      #     Rename-Item -Path $sourcePath -NewName $destFileName
+      - name: Rename APK
+        shell: pwsh
+        run: |
+          $version = '${{ steps.extract_version_windows.outputs.version }}'
+          $build = '${{ steps.extract_version_windows.outputs.build }}'
+          $sourcePath = 'build/app/outputs/flutter-apk/app-release.apk'
+          $destFileName = "Revelation-android-$version-$build.apk"
+          $destPath = "build/app/outputs/flutter-apk/$destFileName"
+          Write-Output "Renaming $sourcePath to $destPath"
+          Rename-Item -Path $sourcePath -NewName $destFileName
 
-      # - name: Build App Bundle (AAB)
-      #   run: flutter build appbundle --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
+      - name: Build App Bundle (AAB)
+        run: flutter build appbundle --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
 
-      # - name: Rename AAB
-      #   shell: pwsh
-      #   run: |
-      #     $version = '${{ steps.extract_version_windows.outputs.version }}'
-      #     $build = '${{ steps.extract_version_windows.outputs.build }}'
-      #     Move-Item -Path 'build/app/outputs/bundle/release/app-release.aab' -Destination "build/app/outputs/bundle/release/Revelation-android-$version-$build.aab"
+      - name: Rename AAB
+        shell: pwsh
+        run: |
+          $version = '${{ steps.extract_version_windows.outputs.version }}'
+          $build = '${{ steps.extract_version_windows.outputs.build }}'
+          Move-Item -Path 'build/app/outputs/bundle/release/app-release.aab' -Destination "build/app/outputs/bundle/release/Revelation-android-$version-$build.aab"
 
-      # - name: Build Windows App
-      #   run: flutter build windows --release --no-tree-shake-icons --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
+      - name: Build Windows App
+        run: flutter build windows --release --no-tree-shake-icons --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
 
-      # - name: Install Inno Setup
-      #   run: |
-      #     choco install innosetup -y
-      #   shell: pwsh
+      - name: Install Inno Setup
+        run: |
+          choco install innosetup -y
+        shell: pwsh
 
-      # - name: Build Installer with Inno Setup
-      #   shell: pwsh
-      #   run: |
-      #     $version = '${{ steps.extract_version_windows.outputs.version }}'
-      #     $build = '${{ steps.extract_version_windows.outputs.build }}'
-      #     $innoSetupScript = 'setup.iss'
-      #     $innoSetupPath = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
-      #     if (!(Test-Path $innoSetupPath)) {
-      #       Write-Error "Inno Setup compiler not found at $innoSetupPath"
-      #       exit 1
-      #     }
-      #     & "$innoSetupPath" "/DMyAppVersion=$version" "/DMyAppBuild=$build" $innoSetupScript
+      - name: Build Installer with Inno Setup
+        shell: pwsh
+        run: |
+          $version = '${{ steps.extract_version_windows.outputs.version }}'
+          $build = '${{ steps.extract_version_windows.outputs.build }}'
+          $innoSetupScript = 'setup.iss'
+          $innoSetupPath = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
+          if (!(Test-Path $innoSetupPath)) {
+            Write-Error "Inno Setup compiler not found at $innoSetupPath"
+            exit 1
+          }
+          & "$innoSetupPath" "/DMyAppVersion=$version" "/DMyAppBuild=$build" $innoSetupScript
 
-      # - name: Upload windows Artifacts
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: build-artifacts
-      #     path: |
-      #       build/app/outputs/flutter-apk/Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.apk
-      #       build/windows/Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.exe
+      - name: Upload windows Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-artifacts
+          path: |
+            build/app/outputs/flutter-apk/Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.apk
+            build/windows/Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.exe
 
-      # - name: Create MSIX Package
-      #   run: dart run msix:create
+      - name: Create MSIX Package
+        run: dart run msix:create
 
-      # - name: Rename MSIX Package
-      #   shell: pwsh
-      #   run: |
-      #     $version = '${{ steps.extract_version_windows.outputs.version }}'
-      #     $build = '${{ steps.extract_version_windows.outputs.build }}'
-      #     Move-Item -Path 'build/windows/x64/runner/Release/revelation.msix' -Destination "build/windows/Revelation-windows-$version-$build.msix"
+      - name: Rename MSIX Package
+        shell: pwsh
+        run: |
+          $version = '${{ steps.extract_version_windows.outputs.version }}'
+          $build = '${{ steps.extract_version_windows.outputs.build }}'
+          Move-Item -Path 'build/windows/x64/runner/Release/revelation.msix' -Destination "build/windows/Revelation-windows-$version-$build.msix"
 
-      # - name: Build web
-      #   run: |
-      #     flutter build web --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
+      - name: Build web
+        run: |
+          flutter build web --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
 
-      # - name: Zip Web Build
-      #   shell: pwsh
-      #   run: |
-      #     $version = '${{ steps.extract_version_windows.outputs.version }}'
-      #     $build   = '${{ steps.extract_version_windows.outputs.build }}'
-      #     $source  = 'build/web'
-      #     $tempDir = 'build/web_temp'
-      #     if (Test-Path $tempDir) {
-      #       Remove-Item $tempDir -Recurse -Force
-      #     }
-      #     New-Item -ItemType Directory -Path $tempDir | Out-Null
-      #     Copy-Item -Path "$source\*" -Destination $tempDir -Recurse -Force
-      #     Compress-Archive -Path "$tempDir\*" -DestinationPath "build/Revelation-web-$version-$build.zip" -Force
-      #     Remove-Item $tempDir -Recurse -Force
+      - name: Zip Web Build
+        shell: pwsh
+        run: |
+          $version = '${{ steps.extract_version_windows.outputs.version }}'
+          $build   = '${{ steps.extract_version_windows.outputs.build }}'
+          $source  = 'build/web'
+          $tempDir = 'build/web_temp'
+          if (Test-Path $tempDir) {
+            Remove-Item $tempDir -Recurse -Force
+          }
+          New-Item -ItemType Directory -Path $tempDir | Out-Null
+          Copy-Item -Path "$source\*" -Destination $tempDir -Recurse -Force
+          Compress-Archive -Path "$tempDir\*" -DestinationPath "build/Revelation-web-$version-$build.zip" -Force
+          Remove-Item $tempDir -Recurse -Force
 
       - name: Create GitHub Release
         id: create_release
@@ -201,55 +201,55 @@ jobs:
           name: upload-url
           path: upload_url.txt
 
-      # - name: Upload APK to Release
-      #   uses: actions/upload-release-asset@v1
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #     asset_path: build/app/outputs/flutter-apk/Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.apk
-      #     asset_name: Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.apk
-      #     asset_content_type: application/vnd.android.package-archive
+      - name: Upload APK to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: build/app/outputs/flutter-apk/Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.apk
+          asset_name: Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.apk
+          asset_content_type: application/vnd.android.package-archive
 
-      # - name: Upload AAB to Release
-      #   uses: actions/upload-release-asset@v1
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #     asset_path: build/app/outputs/bundle/release/Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.aab
-      #     asset_name: Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.aab
-      #     asset_content_type: application/octet-stream
+      - name: Upload AAB to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: build/app/outputs/bundle/release/Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.aab
+          asset_name: Revelation-android-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.aab
+          asset_content_type: application/octet-stream
 
-      # - name: Upload EXE to Release
-      #   uses: actions/upload-release-asset@v1
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #     asset_path: build/windows/Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.exe
-      #     asset_name: Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.exe
-      #     asset_content_type: application/octet-stream
+      - name: Upload EXE to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: build/windows/Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.exe
+          asset_name: Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.exe
+          asset_content_type: application/octet-stream
 
-      # - name: Upload MSIX to Release
-      #   uses: actions/upload-release-asset@v1
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #     asset_path: build/windows/Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.msix
-      #     asset_name: Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.msix
-      #     asset_content_type: application/octet-stream
+      - name: Upload MSIX to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: build/windows/Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.msix
+          asset_name: Revelation-windows-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.msix
+          asset_content_type: application/octet-stream
 
-      # - name: Upload Web ZIP to Release
-      #   uses: actions/upload-release-asset@v1
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #     asset_path: build/Revelation-web-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.zip
-      #     asset_name: Revelation-web-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.zip
-      #     asset_content_type: application/zip
+      - name: Upload Web ZIP to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: build/Revelation-web-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.zip
+          asset_name: Revelation-web-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.zip
+          asset_content_type: application/zip
 
   build-linux:
     runs-on: ubuntu-latest
