Fixed linux bugs

diff --git a/.github/workflows/flutter_build.yml b/.github/workflows/flutter_build.yml
--- a/.github/workflows/flutter_build.yml
+++ b/.github/workflows/flutter_build.yml
@@ -237,6 +237,62 @@ jobs:
           asset_name: Revelation-web-${{ steps.extract_version_windows.outputs.version }}-${{ steps.extract_version_windows.outputs.build }}.zip
           asset_content_type: application/zip
 
+  build-linux:
+    runs-on: ubuntu-latest
+    needs: build-windows
+    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Install Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: "3.32.4"
+          cache: true
+
+      - name: Get Flutter dependencies
+        run: flutter pub get
+
+      - name: Extract version and build number (Linux)
+        id: extract_version_linux
+        run: |
+          if [ ! -f "pubspec.yaml" ]; then
+            echo "pubspec.yaml not found in root directory."
+            exit 1
+          fi
+          version_line=$(grep '^version:' pubspec.yaml)
+          if [[ $version_line =~ ^version:\ ([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+) ]]; then
+            version="${BASH_REMATCH[1]}"
+            build="${BASH_REMATCH[2]}"
+            echo "Extracted version: $version"
+            echo "Extracted build: $build"
+            echo "version=$version" >> $GITHUB_OUTPUT
+            echo "build=$build" >> $GITHUB_OUTPUT
+          else
+            echo "Failed to extract version and build from line: $version_line"
+            exit 1
+          fi
+
+      - name: Build Linux
+        run: flutter build linux --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
+
+      - name: Archive Linux Build
+        run: |
+          version=${{ steps.extract_version_linux.outputs.version }}
+          build=${{ steps.extract_version_linux.outputs.build }}
+          tar -czvf Revelation-linux-$version-$build.tar.gz -C build/linux/x64/release/bundle
+
+      - name: Upload Linux Archive to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ needs.build-windows.outputs.release_upload_url }}
+          asset_path: Revelation-linux-${{ steps.extract_version_linux.outputs.version }}-${{ steps.extract_version_linux.outputs.build }}.tar.gz
+          asset_name: Revelation-linux-${{ steps.extract_version_linux.outputs.version }}-${{ steps.extract_version_linux.outputs.build }}.tar.gz
+          asset_content_type: application/gzip
+
   # build-macos:
   #   runs-on: macos-latest
   #   needs: build-windows
